In [64]:
from vnstock import Trading
trading = Trading(source='VCI') 
df = trading.price_board(symbols_list=['ACB','FPT'])
df.T

                           0       1
listing symbol           ACB     FPT
        ceiling        26000  100200
        floor          22600   87200
        ref_price      24300   93700
        stock_type     STOCK   STOCK
...                      ...     ...
bid_ask ask_1_volume   44500   31600
        ask_2_price    24400   94400
        ask_2_volume  104800   19100
        ask_3_price    24450   94500
        ask_3_volume  188400   23500

[77 rows x 2 columns]

In [65]:
df = trading.price_board(symbols_list=['ACB', 'FPT', 'VIC'])
df = df[[('listing', 'symbol'), ('listing', 'ref_price'), ('match', 'match_price'), ('match', 'accumulated_volume')]]
df.columns = df.columns.droplevel(0)
df['diff'] = round(((df['match_price'] - df['ref_price'])/df['ref_price'])*100, 2)
df['match_price'] = round(df['match_price']/1000, 2)
df['up_down_same'] = [
    'ceiling' if 6.7 <= x <= 7.1 else 
    'floor' if -7.1 <= x <= -6.7 else 
    'up' if x > 0 else 
    'down' if x < 0 else 
    'same' 
    for x in df['diff']
]
df = df.set_index('symbol')
df = df[['match_price', 'accumulated_volume', 'diff', 'up_down_same']]
df

        match_price  accumulated_volume  diff up_down_same
symbol
ACB            24.3             3966200  0.00         same
FPT            94.3             2765700  0.64           up
VIC           167.5             3161800  5.48           up

In [66]:
print(df.loc['FPT']['diff'])

0.64

In [67]:
def status(tickers: list):
    df = trading.price_board(symbols_list=tickers)
    df = df[[('listing', 'symbol'), ('listing', 'ref_price'), ('match', 'match_price'), ('match', 'accumulated_volume')]]
    df.columns = df.columns.droplevel(0)
    df['diff'] = (df['match_price'] - df['ref_price'])/df['ref_price']
    df['up_down_same'] = ['up' if x > 0 else 'down' if x < 0 else 'same' for x in df['diff']]
    df = df.set_index('symbol')
    df = df[['accumulated_volume', 'diff', 'up_down_same']]
    return df